### PR TITLE
Refactored to scrape Yahoo finance instead of using the Alpha Vantage…

### PR DESCRIPTION
**Pull request by patrickjmccauley**
… API due to 1 day lag. Removed Alpha Vantage related code as it's no longer being used, added in BBI as company to data.csv

### CODE REVIEW

**Comment by patrickjmccauley** [comment]
Switched this so that all the querying is now done with web scraping Yahoo finance for the info since Alpha Vantage moved to a 1-day lag on quotes. I also added in a new company to the data.csv file that feeds the tickers.

Could you take a look just to make sure it still works on the Heroku server? No reason it shouldn't, just want to confirm - we no longer need the env variable for the API key, also.

**Comment by woodja** [comment]
@pmccau I tried running this locally and it fails. I get a lot of out of index errors. It's like the span/div ids have all changed and it's no longer parsing the correct data from the page.

**Comment by patrickjmccauley** [comment]
@woodja thanks for testing it - that's odd, I'll troubleshoot a bit

**Comment by patrickjmccauley** [comment]
@woodja This should be fixed - can you try running locally?

**Comment by woodja** [comment]
LGTM
thanks @pmccau

**Pull request merged**
